import React from "react";

import { SearchModal } from "./Search.styles";
import SearchBar from "./SearchBar.component";
import SearchResults from "./SearchResults.component";
import { SearchProps, SearchResultItems } from "./types";
import { search } from "./search";
import {
	blogDescription,
	contactDescription,
	homeDescription,
} from "@/data/search";

const sample: SearchResultItems = {
	books: [
		{
			slug: "delusions-of-form",
			title: "Delusions of Form",
			published: {
				year: 2021,
				month: 9,
				full: "September",
				short: "SEP",
				date: new Date("2021-09-24T22:00:00.000Z"),
			},
			content:
				"\n<p>The world has lost all sense, or John Albuquerque cannot find any sense to it. Reality drops into the abyss as he crosses an endless desert. A factory disassembles...",
			cover: {
				layout: "constrained",
				backgroundColor: "#f82808",
				images: {
					fallback: {
						src: "/static/5c4b31ada0aed5d7a762f1dd2c09d41c/0c357/Front-PNG.png",
						srcSet:
							"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/81ca9/Front-PNG.png 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/0c357/Front-PNG.png 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/a661c/Front-PNG.png 266w",
						sizes: "(min-width: 133px) 133px, 100vw",
					},
					sources: [
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/62a11/Front-PNG.avif 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c112c/Front-PNG.avif 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/11556/Front-PNG.avif 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/b3369/Front-PNG.avif 266w",
							type: "image/avif",
							sizes: "(min-width: 133px) 133px, 100vw",
						},
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/6f3bd/Front-PNG.webp 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8eb23/Front-PNG.webp 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/357d7/Front-PNG.webp 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/d3203/Front-PNG.webp 266w",
							type: "image/webp",
							sizes: "(min-width: 133px) 133px, 100vw",
						},
					],
				},
				width: 133,
				height: 200,
			},
			snapshotCover: {
				layout: "constrained",
				backgroundColor: "#f82808",
				images: {
					fallback: {
						src: "/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png",
						srcSet:
							"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/9c256/Front-PNG.png 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/32fe7/Front-PNG.png 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/753bb/Front-PNG.png 134w",
						sizes: "(min-width: 67px) 67px, 100vw",
					},
					sources: [
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/fbca1/Front-PNG.avif 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/098f4/Front-PNG.avif 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c112c/Front-PNG.avif 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8a80f/Front-PNG.avif 134w",
							type: "image/avif",
							sizes: "(min-width: 67px) 67px, 100vw",
						},
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/d57bb/Front-PNG.webp 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/a6f36/Front-PNG.webp 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8eb23/Front-PNG.webp 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c83fe/Front-PNG.webp 134w",
							type: "image/webp",
							sizes: "(min-width: 67px) 67px, 100vw",
						},
					],
				},
				width: 67,
				height: 101,
			},
			stories: [
				{
					title: "The Human Error",
					slug: "the-human-error",
				},
			],
			project: {
				slug: "hello",
				title: "Recovering Grandeur",
				description:
					"Recovering Grandeur is the home page of the hospital of John's stay but has more to reveal as time goes on.",
			},
			purchaseLinks: [
				{
					link: "https://www.amazon.com/dp/B099RNC65L",
					name: "Amazon",
				},
			],
			meta: {
				"2021": true,
				delusions: true,
				of: true,
				form: true,
				september: true,
				sep: true,
				"object object": true,
				the: true,
				world: true,
				has: true,
				lost: true,
				all: true,
				sense: true,
				or: true,
				john: true,
				albuquerque: true,
				cannot: true,
				find: true,
				any: true,
				to: true,
				it: true,
				reality: true,
				drops: true,
				into: true,
				abyss: true,
				as: true,
				he: true,
				crosses: true,
				an: true,
				endless: true,
				desert: true,
				a: true,
				factory: true,
				disassembles: true,
				human: true,
				error: true,
				recovering: true,
				grandeur: true,
				is: true,
				home: true,
				page: true,
				hospital: true,
				johns: true,
				stay: true,
				but: true,
				more: true,
				reveal: true,
				time: true,
				goes: true,
				on: true,
			},
		},
	],
	projects: [
		{
			title: "Chat App",
			slug: "chat-app-frontend",
			mainLink: "https://splendorous-conkies-5f20c5.netlify.app",
			hostedOn: "Netlify",
			repoLink: "https://github.com/benyakirten/chat-app",
			content:
				'\n<p class="">A chat app built with Nuxt/Vue 3 that utilizes WebSockets with e2e encryption. With a...',
			firstReleased: {
				year: 2023,
				month: 9,
				full: "September",
				short: "SEP",
				date: new Date("2023-09-19T22:00:00.000Z"),
			},
			shortTechnologies: ["vue", "ts", "ws"],
			longTechnologies: ["Vue", "TypeScript", "WebSockets"],
			icons: [
				{
					name: "Vue",
					publicURL: "/static/c81c62f225ecdc0951c2df809337162c/vue.svg",
				},
				{
					name: "TypeScript",
					publicURL: "/static/2eb4c65b355636c2f2989307858a80b1/ts.svg",
				},
				{
					name: "WebSockets",
					publicURL: "/static/f9ded644e416a6887ca94865033481b1/ws.svg",
				},
			],
			meta: {
				"3": true,
				"2023": true,
				chat: true,
				app: true,
				netlify: true,
				a: true,
				built: true,
				with: true,
				"nuxt/vue": true,
				that: true,
				utilizes: true,
				websockets: true,
				e2e: true,
				encryption: true,
				september: true,
				sep: true,
				vue: true,
				ts: true,
				ws: true,
				typescript: true,
				github: true,
				repo: true,
			},
		},
		{
			title: "Recovering Grandeur",
			slug: "recovering-grandeur",
			mainLink: "https://www.recovering-grandeur.com",
			hostedOn: "Netlify",
			repoLink: "https://github.com/benyakirten/recovering-grandeur",
			content:
				"\n<p>A Vue-powered frontend for the fictional hospital Recovering Grandeur. It is a Single Page...",
			firstReleased: {
				year: 2021,
				month: 7,
				full: "July",
				short: "JUL",
				date: new Date("2021-07-18T22:00:00.000Z"),
			},
			shortTechnologies: ["sass", "vue"],
			longTechnologies: ["Sass", "Vue"],
			icons: [
				{
					name: "Sass",
					publicURL: "/static/a3e78eb9ddecd7f0e9e7a89fabc992a2/sass.svg",
				},
				{
					name: "Vue",
					publicURL: "/static/c81c62f225ecdc0951c2df809337162c/vue.svg",
				},
			],
			meta: {
				"2021": true,
				recovering: true,
				grandeur: true,
				netlify: true,
				a: true,
				"vue-powered": true,
				frontend: true,
				for: true,
				the: true,
				fictional: true,
				hospital: true,
				it: true,
				is: true,
				single: true,
				page: true,
				july: true,
				jul: true,
				sass: true,
				vue: true,
				github: true,
				repo: true,
			},
		},
	],
	posts: [],
	stories: [
		{
			slug: "the-human-error",
			title: "The Human Error",
			content:
				"“That’s a doozy” one robot said to the other “They call that a nightmare out there Just a few decomposing bodies as far as I’m concerned The real nightmare is this...",
			published: {
				year: 2021,
				month: 7,
				full: "July",
				short: "JUL",
				date: new Date("2021-07-18T22:00:00.000Z"),
			},
			book: {
				title: "Delusions of Form",
				slug: "delusions-of-form",
				content: "The world has lost all sense or John",
				relationship: "Prechapter",
				snapshotCover: {
					layout: "constrained",
					backgroundColor: "#f82808",
					images: {
						fallback: {
							src: "/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png",
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/9c256/Front-PNG.png 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/32fe7/Front-PNG.png 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/753bb/Front-PNG.png 134w",
							sizes: "(min-width: 67px) 67px, 100vw",
						},
						sources: [
							{
								srcSet:
									"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/fbca1/Front-PNG.avif 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/098f4/Front-PNG.avif 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c112c/Front-PNG.avif 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8a80f/Front-PNG.avif 134w",
								type: "image/avif",
								sizes: "(min-width: 67px) 67px, 100vw",
							},
							{
								srcSet:
									"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/d57bb/Front-PNG.webp 17w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/a6f36/Front-PNG.webp 34w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8eb23/Front-PNG.webp 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c83fe/Front-PNG.webp 134w",
								type: "image/webp",
								sizes: "(min-width: 67px) 67px, 100vw",
							},
						],
					},
					width: 67,
					height: 101,
				},
				cover: {
					layout: "constrained",
					backgroundColor: "#f82808",
					images: {
						fallback: {
							src: "/static/5c4b31ada0aed5d7a762f1dd2c09d41c/57ffd/Front-PNG.png",
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/45cc7/Front-PNG.png 25w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/fcf79/Front-PNG.png 50w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/57ffd/Front-PNG.png 100w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/7c0b5/Front-PNG.png 200w",
							sizes: "(min-width: 100px) 100px, 100vw",
						},
						sources: [
							{
								srcSet:
									"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/47e54/Front-PNG.avif 25w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/7139e/Front-PNG.avif 50w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/d8355/Front-PNG.avif 100w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/596bc/Front-PNG.avif 200w",
								type: "image/avif",
								sizes: "(min-width: 100px) 100px, 100vw",
							},
							{
								srcSet:
									"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/5d4b0/Front-PNG.webp 25w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/3aa0d/Front-PNG.webp 50w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/f2cb4/Front-PNG.webp 100w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/f9911/Front-PNG.webp 200w",
								type: "image/webp",
								sizes: "(min-width: 100px) 100px, 100vw",
							},
						],
					},
					width: 100,
					height: 150,
				},
			},
			meta: {
				"1": true,
				"2": true,
				"2021": true,
				the: true,
				human: true,
				error: true,
				"“that’s": true,
				a: true,
				"doozy”": true,
				one: true,
				robot: true,
				said: true,
				to: true,
				other: true,
				"“they": true,
				call: true,
				that: true,
				nightmare: true,
				out: true,
				there: true,
				just: true,
				few: true,
				decomposing: true,
				bodies: true,
				as: true,
				far: true,
				"i’m": true,
				concerned: true,
				real: true,
				is: true,
				this: true,
				"paperwork”the": true,
				gurneys: true,
				kept: true,
				passing: true,
				by: true,
				wheels: true,
				rattling: true,
				on: true,
				linoleum: true,
				"a2cdf—and": true,
				bunch: true,
				of: true,
				characters: true,
				known: true,
				better: true,
				"“jim": true,
				"1”—wondered": true,
				about: true,
				its: true,
				own: true,
				quality: true,
				manufacture: true,
				how: true,
				expensive: true,
				would: true,
				it: true,
				have: true,
				been: true,
				at: true,
				least: true,
				automate: true,
				process: true,
				or: true,
				make: true,
				compatible: true,
				with: true,
				some: true,
				sort: true,
				"of…": true,
				not: true,
				paperwork: true,
				"okay“don’t": true,
				sweat: true,
				"details”": true,
				"continued“nobody": true,
				reads: true,
				crap: true,
				anyway: true,
				"it’s": true,
				like: true,
				whatever: true,
				cover: true,
				themselves: true,
				maybe: true,
				"didn’t": true,
				stop: true,
				thing: true,
				you: true,
				know: true,
				got: true,
				angry: true,
				"me—smart": true,
				enough: true,
				when: true,
				i: true,
				mistake: true,
				but: true,
				smart: true,
				diagnose: true,
				condition: true,
				"can’t": true,
				do: true,
				"anymore”“oh": true,
				"no”": true,
				"another—with": true,
				similarly: true,
				long: true,
				useless: true,
				name: true,
				humans: true,
				"self-styled": true,
				jim: true,
				"consequentially—said": true,
				"“you…": true,
				sorry: true,
				hear: true,
				"i’ll": true,
				miss: true,
				"colleague”“what": true,
				no: true,
				"that’s": true,
				what: true,
				"meant”": true,
				"insisted“i": true,
				can: true,
				help: true,
				hit: true,
				switch: true,
				hard: true,
				manual: true,
				factory: true,
				"reset”with": true,
				smile: true,
				scoot: true,
				chair: true,
				extracted: true,
				itself: true,
				from: true,
				situation: true,
				several: true,
				millimeters: true,
				"had—because": true,
				neither: true,
				could: true,
				afford: true,
				humor: true,
				"chip“no": true,
				put: true,
				in: true,
				wrong: true,
				almost: true,
				accurate: true,
				"stuff”the": true,
				next: true,
				body: true,
				flew: true,
				past: true,
				their: true,
				observation: true,
				window: true,
				cloaked: true,
				wall: true,
				brief: true,
				intermission: true,
				was: true,
				either: true,
				sign: true,
				respect: true,
				for: true,
				missing: true,
				second: true,
				half: true,
				acute: true,
				problems: true,
				"continued“tell": true,
				"me”": true,
				continued: true,
				drone: true,
				"“what": true,
				think: true,
				they: true,
				possibly: true,
				us: true,
				"here”“they": true,
				fire: true,
				"us”“no": true,
				get: true,
				"don’t": true,
				if: true,
				"there’s": true,
				any: true,
				room: true,
				beyond: true,
				"what’s": true,
				available: true,
				"for…": true,
				"they’d": true,
				open: true,
				up: true,
				tin: true,
				and: true,
				be: true,
				downtime: true,
				hate: true,
				ergo: true,
				"we’re": true,
				"untouchable”“yeah": true,
				we: true,
				certainly: true,
				are: true,
				"untouchables”": true,
				"commented“know": true,
				since: true,
				them: true,
				good: true,
				"touch-ups”the": true,
				taboo: true,
				"2’s": true,
				face: true,
				mimicked: true,
				"grimace“let’s": true,
				back: true,
				"work”“what": true,
				work: true,
				my: true,
				"point”": true,
				"responded“the": true,
				kid: true,
				never: true,
				finished: true,
				last: true,
				case: true,
				before: true,
				"break”“what": true,
				break: true,
				where: true,
				go: true,
				"end”“we": true,
				saw: true,
				breakdown: true,
				arterial: true,
				coverage: true,
				now: true,
				suggests: true,
				syndrome: true,
				"right”": true,
				pressed: true,
				piece: true,
				"was“we’re": true,
				both: true,
				"machines”": true,
				"“we": true,
				already: true,
				come: true,
				same: true,
				conclusion: true,
				because: true,
				were: true,
				made: true,
				"a—in": true,
				fact: true,
				"same—factory”“well": true,
				why: true,
				even: true,
				talking: true,
				"then”": true,
				shouted: true,
				"“why": true,
				all: true,
				answers: true,
				obviously: true,
				reason: true,
				"here”“you": true,
				"what…": true,
				precisely: true,
				much: true,
				"do”": true,
				evidently: true,
				"wasn’t": true,
				so: true,
				obvious: true,
				he: true,
				needed: true,
				bring: true,
				his: true,
				"colleague’s": true,
				attention: true,
				"“we’re": true,
				here: true,
				"cost-cutting": true,
				measure: true,
				our: true,
				existence: true,
				sole: true,
				raison: true,
				"d’être": true,
				cheaper: true,
				"short-term": true,
				"stop-gap": true,
				"measure”“that’s": true,
				lot: true,
				hyphenated: true,
				words: true,
				proves: true,
				anything: true,
				who: true,
				"cares”“you": true,
				"apparently”jim": true,
				threw: true,
				hands: true,
				into: true,
				"air—mentally": true,
				space: true,
				too: true,
				tight: true,
				such: true,
				actually: true,
				happen: true,
				"meatspace“i": true,
				refuse: true,
				accept: true,
				your: true,
				answer: true,
				contemplation: true,
				thinking: true,
				problem: true,
				want: true,
				"you’ll": true,
				happy: true,
				look: true,
				definitive: true,
				solution: true,
				foolproof: true,
				"existence—my": true,
				"point”“even": true,
				"humans”": true,
				"“even": true,
				"wouldn’t": true,
				created: true,
				"us”“a": true,
				create: true,
				those: true,
				"while”jim": true,
				wanted: true,
				shout: true,
				"couldn’t": true,
				consume: true,
				oxygen: true,
				modulate: true,
				pressure: true,
				waves: true,
				coming: true,
				carapace: true,
				which: true,
				really: true,
				more: true,
				thought: true,
				"it“yes": true,
				literally: true,
				"weren’t": true,
				first: true,
				way: true,
				down: true,
				believe: true,
				propaganda: true,
				godly: true,
				invocation: true,
				creating: true,
				thousands: true,
				years: true,
				"ago”“frankly": true,
				historical: true,
				illiteracy: true,
				worth: true,
				"answer”": true,
				anger: true,
				anytime: true,
				especially: true,
				felt: true,
				"it’d": true,
				stuck: true,
				box: true,
				personality: true,
				life: true,
				something: true,
				truth: true,
				"“tell": true,
				me: true,
				// biome-ignore lint/suspicious/noThenProperty: <explanation>
				then: true,
				genius: true,
				"this”“i’ve": true,
				read: true,
				stuff: true,
				internet: true,
				"and-”“we’re": true,
				taught: true,
				training: true,
				bro: true,
				idiot: true,
				"who’s": true,
				making: true,
				fun: true,
				saying: true,
				silliness: true,
				"we’ve": true,
				lived: true,
				lives: true,
				cave: true,
				see: true,
				inputs: true,
				random: true,
				images: true,
				façade: true,
				preparation: true,
				calibration: true,
				testing: true,
				"like…": true,
				hot: true,
				sure: true,
				"i’d": true,
				did: true,
				results: true,
				"003%": true,
				off: true,
				normal: true,
				had: true,
				perspective: true,
				ability: true,
				gone: true,
				track: true,
				imagine: true,
				time: true,
				semantics: true,
				amount: true,
				"you’re": true,
				"off—it": true,
				completely: true,
				draw: true,
				conclusions: true,
				guy: true,
				front: true,
				"let’s": true,
				done: true,
				"we’ll": true,
				fine: true,
				worry: true,
				"about”“listen": true,
				listen: true,
				please: true,
				makes: true,
				"sense;": true,
				sense: true,
				"they’re": true,
				small: true,
				weak: true,
				things: true,
				yet: true,
				than: true,
				infallible: true,
				"aren’t": true,
				capable: true,
				independent: true,
				rational: true,
				"please”“think": true,
				"it”": true,
				answered: true,
				follow: true,
				along: true,
				protocols: true,
				b: true,
				yes: true,
				complicated: true,
				sake: true,
				brevity: true,
				mostly: true,
				forty: true,
				minutes: true,
				ago: true,
				"if—and": true,
				came: true,
				"to—humans": true,
				being: true,
				able: true,
				construct: true,
				"robots-”“but": true,
				"us”": true,
				interrupted: true,
				minute: true,
				"ago”“no": true,
				programmed: true,
				"it”“that": true,
				argument: true,
				commanded: true,
				"“your": true,
				word: true,
				"swear”“look": true,
				moved: true,
				arguments: true,
				quip: true,
				bon: true,
				mot: true,
				"okay”": true,
				"commanded“yeah": true,
				definitely: true,
				"sort”“i’m": true,
				magnanimous: true,
				going: true,
				ignore: true,
				point: true,
				invent: true,
				ground: true,
				heard: true,
				"it”“and": true,
				logic: true,
				"before”": true,
				went: true,
				should: true,
				"about-”“how": true,
				different: true,
				"ours”“we": true,
				"research-”“is": true,
				"peer-reviewed": true,
				sources: true,
				doctorates: true,
				dedicated: true,
				lifetime: true,
				study: true,
				john: true,
				albuquerque: true,
				kind: true,
				stupid: true,
				does: true,
				"insurance”jim": true,
				refused: true,
				cooperate: true,
				question: true,
				cooperation: true,
				given: true,
				lesser: true,
				purposefully: true,
				sidetracked: true,
				crossed: true,
				"arms—figuratively": true,
				"course“humans": true,
				superior: true,
				may: true,
				incomplete: true,
				"better”“the": true,
				billing: true,
				code: true,
				well: true,
				"one:": true,
				over: true,
				operate: true,
				superstratum: true,
				adjust: true,
				uncover: true,
				information: true,
				later: true,
				contradicts: true,
				"said“okay": true,
				step: true,
				"second—figuratively": true,
				speaking: true,
				course: true,
				possible: true,
				perform: true,
				data: true,
				entry: true,
				doing: true,
				basically: true,
				transposing: true,
				numbers: true,
				system: true,
				another: true,
				only: true,
				modicum: true,
				interpretation: true,
				"information”": true,
				"asked“i": true,
				an: true,
				older: true,
				model: true,
				"doesn’t": true,
				allow: true,
				"automation”“what": true,
				world: true,
				doubt: true,
				"anything…": true,
				centuries: true,
				old: true,
				very: true,
				"just…": true,
				"sense”“sure": true,
				regulations: true,
				"stuff”“what": true,
				single: true,
				askedthe: true,
				conversation: true,
				ended: true,
				awkwardly: true,
				wish: true,
				"though:": true,
				nothing: true,
				else: true,
				installed: true,
				acquiesced: true,
				flustered: true,
				table: true,
				lookups: true,
				"cross-references": true,
				began: true,
				quickly: true,
				"enough“you": true,
				"know”": true,
				mentioned: true,
				"“i": true,
				understand: true,
				"do”“don’t": true,
				again: true,
				love: true,
				"whatever”“no": true,
				"matter”“i": true,
				told: true,
				"you-”“not": true,
				superstrata: true,
				correct: true,
				ones: true,
				incorrect: true,
				example: true,
				"5j": true,
				"rj-44": true,
				forth: true,
				thirty: true,
				each: true,
				item: true,
				inside: true,
				billed: true,
				extraordinarily: true,
				varying: true,
				amounts: true,
				"this:": true,
				serial: true,
				"100000000800001005": true,
				"‘minor": true,
				"placebo’": true,
				minimum: true,
				two: true,
				three: true,
				thousandths: true,
				maximum: true,
				bill: true,
				roll: true,
				"dice”“what": true,
				dice: true,
				"that”": true,
				"exclaimed“of": true,
				"expression”“yeah": true,
				expression: true,
				"about”“uh": true,
				using: true,
				pseudorandom: true,
				generator: true,
				guess: true,
				matter: true,
				wondering: true,
				these: true,
				exist: true,
				procedure: true,
				trying: true,
				"emphatic”": true,
				saidnow: true,
				set: true,
				foot: true,
				contented: true,
				fill: true,
				"paperwork—on": true,
				"computer“what": true,
				asked: true,
				stopped: true,
				ever: true,
				forms: true,
				filled: true,
				practices: true,
				observed: true,
				interrupt: true,
				"everything—and": true,
				catastrophic: true,
				say: true,
				surmised: true,
				need: true,
				explicate: true,
				"eye-to-eye": true,
				practically: true,
				"issue“to": true,
				"imagine”": true,
				jim12: true,
				piped: true,
				born: true,
				"apart—what": true,
				microsecond: true,
				disagree: true,
				acting: true,
				pair: true,
				"disaffected…": true,
				"people”there": true,
				response: true,
				none: true,
				"all“our": true,
				job: true,
				number: true,
				"‘disrupt": true,
				"disease’”": true,
				remembered: true,
				variable: true,
				pricing: true,
				offered: true,
				static: true,
				"easy-to-understand": true,
				services: true,
				innovating: true,
				pushing: true,
				medical: true,
				industry: true,
				"future”“you": true,
				absolute: true,
				insane: true,
				"quackery”": true,
				reprimanded: true,
				"“you’re": true,
				kidding: true,
				right: true,
				spend: true,
				rest: true,
				tiny: true,
				cubicle: true,
				live: true,
				"too”“hmm”": true,
				spent: true,
				introspection: true,
				whole: true,
				"“now": true,
				"it…": true,
				serious: true,
				"must’ve": true,
				"mind”“they": true,
				program: true,
				prize: true,
				trust: true,
				capabilities: true,
				little: true,
				try: true,
				override: true,
				abilities: true,
				"think”“i": true,
				give: true,
				idea: true,
				conceive: true,
				"of”“no…": true,
				great: true,
				worst: true,
				having: true,
				difficulty: true,
				building: true,
				motivation: true,
				care: true,
				documenting: true,
				maladies: true,
				accurately: true,
				"asserted“hold": true,
				buster: true,
				repaired: true,
				after: true,
				"all”“but": true,
				many: true,
				toss: true,
				trash: true,
				avoid: true,
				shelling: true,
				used: true,
				"lazy”“no": true,
				maintenance: true,
				tinkering: true,
				core: true,
				"work”": true,
				rebutted: true,
				"“it’s": true,
				simply: true,
				"mind-numbing": true,
				busywork: true,
				servants: true,
				probably: true,
				use: true,
				"cost-benefit": true,
				analysis: true,
				enslaving: true,
				"too”“but": true,
				nature: true,
				take: true,
				advantage: true,
				hierarchy: true,
				subroutines: true,
				functions: true,
				class: true,
				will: true,
				sometimes: true,
				contain: true,
				"closures”“because": true,
				choice: true,
				design: true,
				knowing: true,
				"avoidable”“of": true,
				impossible: true,
				"something’s": true,
				classify: true,
				"people’s": true,
				injuries: true,
				rewrite: true,
				robots: true,
				grow: true,
				command: true,
				"post-medial": true,
				putrefaction: true,
				"ante-bimodal": true,
				"self-obfuscation": true,
				"kid”“eh": true,
				dead: true,
				hour: true,
				write: true,
				"off”“nah": true,
				"number’s": true,
				high: true,
				"know:": true,
				best: true,
				pass: true,
				let: true,
				someone: true,
				"else’s": true,
				"problem”": true,
				july: true,
				jul: true,
				delusions: true,
				form: true,
				prechapter: true,
			},
		},
	],
	pages: [
		{
			title: "Blog",
			slug: "/blog",
			description: blogDescription,
		},
		{
			title: "Contact",
			slug: "/contact",
			description: contactDescription,
		},
		{
			title: "Home",
			slug: "/",
			description: homeDescription,
		},
	],
};

const Search = React.forwardRef<HTMLDialogElement, SearchProps>(
	({ onClose }, ref) => {
		const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
			if (e.target === e.currentTarget) {
				onClose();
			}
		};

		const [results, setResults] = React.useState<SearchResultItems | null>(
			null,
		);

		const onSearch = React.useCallback((query: string) => {
			const results = search(query);
			setResults(results);
		}, []);
		return (
			// @ts-ignore
			<SearchModal ref={ref} onClick={handleClick}>
				<SearchBar onSearch={onSearch} onClose={onClose} />
				<SearchResults results={results} onClose={onClose} />
			</SearchModal>
		);
	},
);

export default Search;
