import React from "react";

import { SearchModal } from "./Search.styles";
import SearchBar from "./SearchBar.component";
import SearchResults from "./SearchResults.component";
import { SearchProps, SearchResultItems } from "./types";
import { search } from "./search";
import {
	blogDescription,
	contactDescription,
	homeDescription,
} from "@/data/search";

const sample: SearchResultItems = {
	books: [
		{
			slug: "delusions-of-form",
			title: "Delusions of Form",
			published: {
				year: 2021,
				month: 9,
				full: "September",
				short: "SEP",
				date: new Date("2021-09-24T22:00:00.000Z"),
			},
			content:
				"\n<p>The world has lost all sense, or John Albuquerque cannot find any sense to it. Reality drops into the abyss as he crosses an endless desert. A factory disassembles...",
			cover: {
				layout: "constrained",
				backgroundColor: "#f82808",
				images: {
					fallback: {
						src: "/static/5c4b31ada0aed5d7a762f1dd2c09d41c/0c357/Front-PNG.png",
						srcSet:
							"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/81ca9/Front-PNG.png 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c7a07/Front-PNG.png 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/0c357/Front-PNG.png 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/a661c/Front-PNG.png 266w",
						sizes: "(min-width: 133px) 133px, 100vw",
					},
					sources: [
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/62a11/Front-PNG.avif 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/c112c/Front-PNG.avif 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/11556/Front-PNG.avif 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/b3369/Front-PNG.avif 266w",
							type: "image/avif",
							sizes: "(min-width: 133px) 133px, 100vw",
						},
						{
							srcSet:
								"/static/5c4b31ada0aed5d7a762f1dd2c09d41c/6f3bd/Front-PNG.webp 33w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/8eb23/Front-PNG.webp 67w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/357d7/Front-PNG.webp 133w,\n/static/5c4b31ada0aed5d7a762f1dd2c09d41c/d3203/Front-PNG.webp 266w",
							type: "image/webp",
							sizes: "(min-width: 133px) 133px, 100vw",
						},
					],
				},
				width: 133,
				height: 200,
			},
			stories: [
				{
					title: "The Human Error",
					slug: "the-human-error",
				},
			],
			// @ts-ignore
			project: {
				title: "Recovering Grandeur",
				description:
					"Recovering Grandeur is the home page of the hospital of John's stay but has more to reveal as time goes on.",
			},
			purchaseLinks: [
				{
					link: "https://www.amazon.com/dp/B099RNC65L",
					name: "Amazon",
				},
			],
			meta: {
				"2021": true,
				delusions: true,
				of: true,
				form: true,
				september: true,
				sep: true,
				"object object": true,
				the: true,
				world: true,
				has: true,
				lost: true,
				all: true,
				sense: true,
				or: true,
				john: true,
				albuquerque: true,
				cannot: true,
				find: true,
				any: true,
				to: true,
				it: true,
				reality: true,
				drops: true,
				into: true,
				abyss: true,
				as: true,
				he: true,
				crosses: true,
				an: true,
				endless: true,
				desert: true,
				a: true,
				factory: true,
				disassembles: true,
				human: true,
				error: true,
				recovering: true,
				grandeur: true,
				is: true,
				home: true,
				page: true,
				hospital: true,
				johns: true,
				stay: true,
				but: true,
				more: true,
				reveal: true,
				time: true,
				goes: true,
				on: true,
			},
		},
	],
	projects: [
		{
			title: "Chat App",
			slug: "chat-app-frontend",
			mainLink: "https://splendorous-conkies-5f20c5.netlify.app",
			hostedOn: "Netlify",
			repoLink: "https://github.com/benyakirten/chat-app",
			content:
				'\n<p class="">A chat app built with Nuxt/Vue 3 that utilizes WebSockets with e2e encryption. With a...',
			firstReleased: {
				year: 2023,
				month: 9,
				full: "September",
				short: "SEP",
				date: new Date("2023-09-19T22:00:00.000Z"),
			},
			shortTechnologies: ["vue", "ts", "ws"],
			longTechnologies: ["Vue", "TypeScript", "WebSockets"],
			icons: [
				{
					name: "Vue",
					publicURL: "/static/c81c62f225ecdc0951c2df809337162c/vue.svg",
				},
				{
					name: "TypeScript",
					publicURL: "/static/2eb4c65b355636c2f2989307858a80b1/ts.svg",
				},
				{
					name: "WebSockets",
					publicURL: "/static/f9ded644e416a6887ca94865033481b1/ws.svg",
				},
			],
			meta: {
				"3": true,
				"2023": true,
				chat: true,
				app: true,
				netlify: true,
				a: true,
				built: true,
				with: true,
				"nuxt/vue": true,
				that: true,
				utilizes: true,
				websockets: true,
				e2e: true,
				encryption: true,
				september: true,
				sep: true,
				vue: true,
				ts: true,
				ws: true,
				typescript: true,
				github: true,
				repo: true,
			},
		},
		{
			title: "Recovering Grandeur",
			slug: "recovering-grandeur",
			mainLink: "https://www.recovering-grandeur.com",
			hostedOn: "Netlify",
			repoLink: "https://github.com/benyakirten/recovering-grandeur",
			content:
				"\n<p>A Vue-powered frontend for the fictional hospital Recovering Grandeur. It is a Single Page...",
			firstReleased: {
				year: 2021,
				month: 7,
				full: "July",
				short: "JUL",
				date: new Date("2021-07-18T22:00:00.000Z"),
			},
			shortTechnologies: ["sass", "vue"],
			longTechnologies: ["Sass", "Vue"],
			icons: [
				{
					name: "Sass",
					publicURL: "/static/a3e78eb9ddecd7f0e9e7a89fabc992a2/sass.svg",
				},
				{
					name: "Vue",
					publicURL: "/static/c81c62f225ecdc0951c2df809337162c/vue.svg",
				},
			],
			meta: {
				"2021": true,
				recovering: true,
				grandeur: true,
				netlify: true,
				a: true,
				"vue-powered": true,
				frontend: true,
				for: true,
				the: true,
				fictional: true,
				hospital: true,
				it: true,
				is: true,
				single: true,
				page: true,
				july: true,
				jul: true,
				sass: true,
				vue: true,
				github: true,
				repo: true,
			},
		},
	],
	posts: [],
	stories: [
		{
			slug: "non-sequitur-a-pre-chapter-to-the-human-automata",
			title: "Non-sequitur",
			content:
				"He was the last human in the factory to observe the old machine and how it had somehow gone beyond rust to fermentation It was noticeable pungent and off-putting yet...",
			published: {
				year: 2020,
				month: 8,
				full: "August",
				short: "AUG",
				date: new Date("2020-08-19T22:00:00.000Z"),
			},
			book: {
				title: "The Human Automata",
				slug: "the-human-automata",
				content: "Jules Winters is certain of his destiny to",
				relationship: "Pre-chapter",
				cover: {
					layout: "constrained",
					backgroundColor: "#e8e8e8",
					images: {
						fallback: {
							src: "/static/177917fb694b25340da5a05e9d8539ca/c7045/cover-scaled.jpg",
							srcSet:
								"/static/177917fb694b25340da5a05e9d8539ca/60dbf/cover-scaled.jpg 26w,\n/static/177917fb694b25340da5a05e9d8539ca/9709e/cover-scaled.jpg 52w,\n/static/177917fb694b25340da5a05e9d8539ca/c7045/cover-scaled.jpg 103w,\n/static/177917fb694b25340da5a05e9d8539ca/a5816/cover-scaled.jpg 206w",
							sizes: "(min-width: 103px) 103px, 100vw",
						},
						sources: [
							{
								srcSet:
									"/static/177917fb694b25340da5a05e9d8539ca/3d8c9/cover-scaled.avif 26w,\n/static/177917fb694b25340da5a05e9d8539ca/36b62/cover-scaled.avif 52w,\n/static/177917fb694b25340da5a05e9d8539ca/f3c50/cover-scaled.avif 103w,\n/static/177917fb694b25340da5a05e9d8539ca/0c8e8/cover-scaled.avif 206w",
								type: "image/avif",
								sizes: "(min-width: 103px) 103px, 100vw",
							},
							{
								srcSet:
									"/static/177917fb694b25340da5a05e9d8539ca/6ca1a/cover-scaled.webp 26w,\n/static/177917fb694b25340da5a05e9d8539ca/34839/cover-scaled.webp 52w,\n/static/177917fb694b25340da5a05e9d8539ca/c0a7b/cover-scaled.webp 103w,\n/static/177917fb694b25340da5a05e9d8539ca/77343/cover-scaled.webp 206w",
								type: "image/webp",
								sizes: "(min-width: 103px) 103px, 100vw",
							},
						],
					},
					width: 103,
					height: 151,
				},
			},
			meta: {
				"2020": true,
				"non-sequitur": true,
				he: true,
				was: true,
				the: true,
				last: true,
				human: true,
				in: true,
				factory: true,
				to: true,
				observe: true,
				old: true,
				machine: true,
				and: true,
				how: true,
				it: true,
				had: true,
				somehow: true,
				gone: true,
				beyond: true,
				rust: true,
				fermentation: true,
				noticeable: true,
				pungent: true,
				"off-putting": true,
				yet: true,
				nothing: true,
				ever: true,
				done: true,
				despite: true,
				facility: true,
				grew: true,
				its: true,
				millions: true,
				of: true,
				square: true,
				metersthe: true,
				bucket: true,
				rotten: true,
				bolts: true,
				inspired: true,
				some: true,
				strange: true,
				sympathy: true,
				having: true,
				worked: true,
				alongside: true,
				him: true,
				for: true,
				so: true,
				long: true,
				both: true,
				been: true,
				every: true,
				"person’s": true,
				sight: true,
				before: true,
				entering: true,
				euphemism: true,
				"self-fulfillment": true,
				center: true,
				on: true,
				left: true,
				right: true,
				but: true,
				now: true,
				too: true,
				summoned: true,
				that: true,
				infamous: true,
				nadir: true,
				as: true,
				his: true,
				defunct: true,
				coworker: true,
				did: true,
				nothingas: true,
				crossed: true,
				few: true,
				steps: true,
				an: true,
				odd: true,
				assembly: true,
				words: true,
				appeared: true,
				mind: true,
				stopped: true,
				read: true,
				them: true,
				himself: true,
				at: true,
				first: true,
				// biome-ignore lint/suspicious/noThenProperty: <explanation>
				then: true,
				aloud: true,
				a: true,
				second: true,
				time: true,
				fearing: true,
				"misunderstood“all": true,
				humans: true,
				are: true,
				approach: true,
				breathe: true,
				deep: true,
				this: true,
				"tredger’s": true,
				history: true,
				your: true,
				happiness: true,
				assessment: true,
				no: true,
				is: true,
				not: true,
				joke: true,
				"you’re": true,
				supposed: true,
				do: true,
				"literally”the": true,
				sentence: true,
				raised: true,
				very: true,
				questions: true,
				aimed: true,
				answer: true,
				obeyed: true,
				bowed: true,
				down: true,
				end: true,
				"couldn’t": true,
				help: true,
				wince: true,
				inhaled: true,
				putridity: true,
				what: true,
				believed: true,
				most: true,
				dignified: true,
				way: true,
				possiblehe: true,
				straightened: true,
				facial: true,
				expression: true,
				back: true,
				with: true,
				difficulty: true,
				man: true,
				sometimes: true,
				wanted: true,
				question: true,
				"body’s": true,
				senescence: true,
				if: true,
				each: true,
				"day’s": true,
				responsibilities: true,
				work: true,
				may: true,
				have: true,
				hand: true,
				position: true,
				sohe: true,
				hesitated: true,
				contemplating: true,
				destination: true,
				happy: true,
				outcome: true,
				come: true,
				liminal: true,
				space: true,
				encroaching: true,
				upon: true,
				nevertheless: true,
				able: true,
				suppress: true,
				doubts: true,
				cross: true,
				threshold: true,
				"professionalism’s": true,
				"sake“hello”": true,
				cheery: true,
				voice: true,
				said: true,
				soon: true,
				door: true,
				closed: true,
				firmly: true,
				behind: true,
				chamber: true,
				awfully: true,
				cramped: true,
				only: true,
				enough: true,
				room: true,
				stand: true,
				more: true,
				offer: true,
				chair: true,
				or: true,
				knowledge: true,
				source: true,
				"would’ve": true,
				known: true,
				either: true,
				"“this": true,
				mark: true,
				five: true,
				resources: true,
				automaton: true,
				call: true,
				me: true,
				"mark”“hi": true,
				"mark”": true,
				"said”i’m-”“hi”": true,
				interrupted: true,
				"“please": true,
				"sir”“i’m": true,
				"here”": true,
				pressed: true,
				"“serial": true,
				number: true,
				uh: true,
				"jdfg//gu15ili": true,
				i: true,
				filed: true,
				"a-”“yeah”": true,
				once: true,
				again: true,
				testily: true,
				"“i": true,
				know: true,
				all: true,
				about: true,
				albert: true,
				winters: true,
				yours: true,
				seems: true,
				almost: true,
				interesting: true,
				name: true,
				"doesn’t": true,
				"it”“i": true,
				never: true,
				thought: true,
				"request-”“too": true,
				bad: true,
				"it’s": true,
				easier: true,
				you: true,
				by: true,
				serial: true,
				"number”“uh": true,
				"okay-”“you": true,
				"don’t": true,
				get: true,
				"you”": true,
				burst: true,
				forth: true,
				method: true,
				speaking: true,
				over: true,
				seemed: true,
				be: true,
				normal: true,
				operation: true,
				"“just": true,
				because: true,
				"i’m": true,
				mean: true,
				"shouldn’t": true,
				sir: true,
				due: true,
				respect: true,
				my: true,
				"no”“i": true,
				"didn’t": true,
				even: true,
				were: true,
				"computer”": true,
				responded: true,
				felt: true,
				warm: true,
				booth: true,
				stop: true,
				pores: true,
				would: true,
				"open“even": true,
				evidence: true,
				should: true,
				say: true,
				"it”": true,
				scolded: true,
				hate: true,
				go: true,
				evaluation: true,
				regardless: true,
				disrespect: true,
				"me-”“i": true,
				assure: true,
				simple: true,
				"error-”": true,
				tried: true,
				"respond“but": true,
				important: true,
				thing: true,
				whether: true,
				can: true,
				along: true,
				robots: true,
				"jdfg//": true,
				et: true,
				cetera: true,
				terrible: true,
				prospects: true,
				people: true,
				think: true,
				difficult: true,
				fearful: true,
				inferiority: true,
				spiteful: true,
				our: true,
				"superiority”“sir": true,
				madame: true,
				whatever: true,
				preferred: true,
				appellation: true,
				"you-”“this": true,
				traditional: true,
				workplace: true,
				need: true,
				remind: true,
				"you”“yes": true,
				am: true,
				sorry: true,
				"sir”": true,
				guessed: true,
				though: true,
				true: true,
				objection: true,
				meant: true,
				meantime: true,
				losing: true,
				scarce: true,
				water: true,
				weight: true,
				great: true,
				drops: true,
				sweat: true,
				hoped: true,
				adapt: true,
				good: true,
				least: true,
				when: true,
				chances: true,
				"weren’t": true,
				unfairresigned: true,
				subservience: true,
				overlords: true,
				understand: true,
				why: true,
				extra: true,
				layer: true,
				friction: true,
				unnecessary: true,
				"opponent—such": true,
				situation: true,
				necessarily: true,
				required: true,
				adversarial: true,
				relationship: true,
				between: true,
				workers: true,
				bosses: true,
				fact: true,
				"that’s": true,
				relationships: true,
				"not—could": true,
				just: true,
				tell: true,
				state: true,
				application: true,
				reason: true,
				"there“can": true,
				we: true,
				talk: true,
				"happened”": true,
				asked: true,
				lull: true,
				getting: true,
				hot: true,
				breath: true,
				persisted: true,
				"“that": true,
				paperwork: true,
				stuff: true,
				submitted: true,
				home: true,
				half: true,
				hour: true,
				early: true,
				two: true,
				days: true,
				less: true,
				than: true,
				meeting: true,
				"i’ll": true,
				make: true,
				up: true,
				any: true,
				short: true,
				please: true,
				"sir…": true,
				"think”“that": true,
				"isn’t": true,
				"point”": true,
				reprimanded: true,
				"“it’s": true,
				discussion: true,
				loyalty: true,
				"maxgun::happy": true,
				"idea…": true,
				already: true,
				giving: true,
				"110%": true,
				times: true,
				logical: true,
				impossibility: true,
				unless: true,
				dare: true,
				impute: true,
				suggest: true,
				"anything…": true,
				minute: true,
				shown: true,
				often: true,
				lay: true,
				out: true,
				their: true,
				ideas: true,
				properly: true,
				psychology: true,
				believe: true,
				called: true,
				honest: true,
				guess: true,
				matter: true,
				jay: true,
				dee: true,
				truly: true,
				want: true,
				asking: true,
				exception: true,
				there: true,
				something: true,
				wrong: true,
				life: true,
				"why—and": true,
				ask: true,
				who: true,
				enter: true,
				"office—why": true,
				excuse: true,
				lollygag: true,
				logic: true,
				being: true,
				equanimous: true,
				"i’d": true,
				cut: true,
				"everyone’s": true,
				hours: true,
				"can’t": true,
				"you”“i’ve": true,
				really: true,
				got: true,
				son: true,
				"he’s-”“you": true,
				rant: true,
				lot: true,
				"god”": true,
				"“yeah": true,
				"i’ve": true,
				looked: true,
				sent: true,
				denied: true,
				going: true,
				possible: true,
				talking: true,
				dire: true,
				care: true,
				"right”“yes": true,
				family: true,
				afford: true,
				"to…”": true,
				reformulated: true,
				clothes: true,
				soaked: true,
				continued: true,
				"“there’s": true,
				"all’s": true,
				fine: true,
				"sir”“good": true,
				withdrawing: true,
				real: true,
				team: true,
				player: true,
				distracted: true,
				while: true,
				working: true,
				correct: true,
				whole: true,
				"thing’s": true,
				vital: true,
				everyone: true,
				puts: true,
				appropriate: true,
				effort: true,
				like: true,
				suddenly: true,
				tolerate: true,
				"073%": true,
				"9511%": true,
				decrease: true,
				output: true,
				from: true,
				"ninety-three": true,
				employees: true,
				depending: true,
				function: true,
				role: true,
				tight: true,
				margins: true,
				where: true,
				coming: true,
				severely: true,
				issue: true,
				above: true,
				head: true,
				"all”to": true,
				maybe: true,
				else: true,
				such: true,
				legs: true,
				cramping: true,
				sighed: true,
				let: true,
				happen: true,
				slowly: true,
				realized: true,
				"wasn’t": true,
				actually: true,
				"he’d": true,
				intended: true,
				desired: true,
				effect: true,
				inappropriate: true,
				judging: true,
				lack: true,
				noise: true,
				conversational: true,
				counterpart: true,
				"booth’s": true,
				emit: true,
				fuzz: true,
				breathing: true,
				absent: true,
				"mm-hmm": true,
				desperately: true,
				regretted: true,
				action: true,
				take: true,
				stupid: true,
				deserved: true,
				"coming“you": true,
				thinking: true,
				give: true,
				off: true,
				approval: true,
				policy: true,
				anyone: true,
				"who’s": true,
				government: true,
				guarantee: true,
				needs: true,
				"tested”“tested”": true,
				superfluous: true,
				knew: true,
				exactly: true,
				milled: true,
				wondered: true,
				misstepped: true,
				moment: true,
				desperation: true,
				accepted: true,
				job: true,
				gotten: true,
				stuck: true,
				blame: true,
				ended: true,
				upit: true,
				advancement: true,
				finished: true,
				somewhere: true,
				better: true,
				spite: true,
				other: true,
				recipient: true,
				"resentment:": true,
				needy: true,
				kid: true,
				father: true,
				held: true,
				much: true,
				everywhere: true,
				needed: true,
				drain: true,
				passions: true,
				paying: true,
				attention: true,
				those: true,
				obligated: true,
				sothere: true,
				indeed: true,
				chance: true,
				occasion: true,
				passed: true,
				grab: true,
				success: true,
				"again“well": true,
				"several”": true,
				"“the": true,
				popular: true,
				means: true,
				testing: true,
				"course”he": true,
				found: true,
				adversary: true,
				arbiter: true,
				"society’s": true,
				unfairness: true,
				blocking: true,
				ascendence: true,
				one: true,
				taken: true,
				advantage: true,
				system: true,
				person: true,
				addressed: true,
				made: true,
				accomplished: true,
				heart: true,
				cared: true,
				punished: true,
				could: true,
				bring: true,
				uncalled: true,
				"for:": true,
				purge: true,
				chaff: true,
				"was“if": true,
				still: true,
				"hard”": true,
				"“is": true,
				"think…": true,
				"money”“yeah": true,
				latter: true,
				gist: true,
				"it”“given": true,
				income: true,
				sound: true,
				kinda: true,
				"self-defeating": true,
				also: true,
				look: true,
				"the…": true,
				paystubs: true,
				exam: true,
				see: true,
				applies: true,
				yes: true,
				using: true,
				information: true,
				"possess”“well”": true,
				cleared: true,
				incorporeal: true,
				throat: true,
				"“that’s": true,
				doing: true,
				paycheck: true,
				binary: true,
				finding: true,
				many: true,
				things: true,
				besides: true,
				running: true,
				side: true,
				jobs: true,
				"rest”“isn’t": true,
				"“i’m": true,
				putting: true,
				myself: true,
				making: true,
				independent: true,
				bailing: true,
				course: true,
				put: true,
				danger: true,
				hard: true,
				best: true,
				turn: true,
				came: true,
				lottery: true,
				"course”“believe": true,
				productive: true,
				member: true,
				society: true,
				"get-up": true,
				pull: true,
				yourself: true,
				bootstraps: true,
				always: true,
				telling: true,
				colleagues: true,
				regulations: true,
				"they’re": true,
				awful: true,
				especially: true,
				they: true,
				involved: true,
				might: true,
				has: true,
				employment: true,
				here: true,
				these: true,
				okay: true,
				"let’s": true,
				quick: true,
				"easy”“of": true,
				"best”by": true,
				feeling: true,
				extremities: true,
				little: true,
				ventilation: true,
				none: true,
				afraid: true,
				into: true,
				"room’s": true,
				natural: true,
				limit: true,
				through: true,
				"oxygen“first": true,
				"fridge”": true,
				askedthe: true,
				took: true,
				comprehend: true,
				figure: true,
				leading: true,
				seem: true,
				interact: true,
				significant: true,
				audacity: true,
				representative: true,
				bureaucracy: true,
				"government-inspired": true,
				apathy: true,
				opposed: true,
				fight: true,
				resist: true,
				mentality: true,
				clear: true,
				stating: true,
				anything: true,
				simply: true,
				"life“no": true,
				"personally”": true,
				remembered: true,
				included: true,
				"“sir”“but": true,
				eat: true,
				fresh: true,
				refrigerated: true,
				incontrovertible: true,
				excretory: true,
				production: true,
				does: true,
				support: true,
				spoiled: true,
				backslash: true,
				usually: true,
				use: true,
				nicknames: true,
				aka: true,
				"pseudonyms”“no": true,
				al: true,
				nobody: true,
				calls: true,
				syllables: true,
				untrustworthy: true,
				control: true,
				blabbering: true,
				eating: true,
				"synthetic-meat-like": true,
				protein: true,
				pastes: true,
				"there’s": true,
				small: true,
				community: true,
				refrigerator: true,
				near: true,
				kilometer: true,
				walk: true,
				trying: true,
				lease: true,
				friend: true,
				share: true,
				nice: true,
				"expect”“mm-hmm": true,
				crux: true,
				problem: true,
				potential: true,
				value: true,
				"is”“but”": true,
				objected: true,
				"“there": true,
				reasons: true,
				unique: true,
				counted: true,
				against: true,
				access: true,
				letter: true,
				without: true,
				practicality: true,
				listen: true,
				"sir”he": true,
				performative: true,
				mouth: true,
				heartfully: true,
				express: true,
				grim: true,
				worthlessness: true,
				compelled: true,
				insincere: true,
				sincere: true,
				same: true,
				wordsprior: true,
				occur: true,
				desires: true,
				genuine: true,
				odds: true,
				contradiction: true,
				statement: true,
				personal: true,
				philosophies: true,
				further: true,
				convictions: true,
				fundamental: true,
				beliefs: true,
				themselves: true,
				flawed: true,
				after: true,
				lead: true,
				questioning: true,
				therefore: true,
				sleeping: true,
				dogs: true,
				"lie“i’ll": true,
				direct: true,
				"question”": true,
				commanded: true,
				"“how": true,
				"worth”“i": true,
				idea: true,
				wage: true,
				"days”“per": true,
				hah: true,
				nowhere: true,
				"that”“is": true,
				"less”": true,
				"asked“sir": true,
				"sir”“does": true,
				disqualify: true,
				"me”": true,
				sharp: true,
				pain: true,
				struggled: true,
				proud: true,
				remarkably: true,
				cohesive: true,
				arguments: true,
				far: true,
				allowed: true,
				"could’ve": true,
				misevaluated: true,
				foot: true,
				"be“how": true,
				drunk: true,
				"high”": true,
				"asked“i’d": true,
				"never”": true,
				blathered: true,
				repeating: true,
				nervousness: true,
				sort: true,
				failing: true,
				needing: true,
				empty: true,
				bladder: true,
				which: true,
				coincidentally: true,
				urge: true,
				"moment“we’ll": true,
				insert: true,
				probes: true,
				place: true,
				begin: true,
				"nature’s": true,
				"obliges”": true,
				evidently: true,
				aware: true,
				desire: true,
				eliminationthere: true,
				hardly: true,
				fiddle: true,
				imagine: true,
				mouthed: true,
				wall: true,
				became: true,
				miserable: true,
				shame: true,
				castigated: true,
				quietly: true,
				muttering: true,
				react: true,
				eventually: true,
				"succeeded“employee”": true,
				barked: true,
				satisfied: true,
				"this”“what”": true,
				answered: true,
				"“doing": true,
				smelled: true,
				alcohol: true,
				sure: true,
				reading: true,
				beg: true,
				knees: true,
				hands: true,
				together: true,
				pitiable: true,
				gesture: true,
				instead: true,
				lightly: true,
				banged: true,
				cubicle: true,
				walls: true,
				noted: true,
				"else“i’ll": true,
				pleaded: true,
				imperil: true,
				opportunities: true,
				"hard-working": true,
				ones: true,
				count: true,
				"must’ve": true,
				tredger: true,
				museum: true,
				piece: true,
				"outside”<p": true,
				"class=has-medium-font-size>the": true,
				respond: true,
				doors: true,
				opened: true,
				dazed: true,
				senses: true,
				armed: true,
				aiming: true,
				possibly: true,
				belief: true,
				"man<hr": true,
				"class=wp-block-separator/><p": true,
				"class=has-medium-font-size>if": true,
				enjoyed: true,
				story: true,
				alberts: true,
				automata: true,
				purchase: true,
				amazon: true,
				ill: true,
				free: true,
				august: true,
				aug: true,
				"pre-chapter": true,
			},
		},
	],
	pages: [
		{
			title: "Blog",
			slug: "/blog",
			description: blogDescription,
		},
		{
			title: "Contact",
			slug: "/contact",
			description: contactDescription,
		},
		{
			title: "Home",
			slug: "/",
			description: homeDescription,
		},
	],
};

const Search = React.forwardRef<HTMLDialogElement, SearchProps>(
	({ onClose }, ref) => {
		const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
			if (e.target === e.currentTarget) {
				onClose();
			}
		};

		const [results, setResults] = React.useState<SearchResultItems | null>(
			sample,
		);

		const onSearch = React.useCallback((query: string) => {
			const results = search(query);
			setResults(results);
		}, []);
		return (
			// @ts-ignore
			<SearchModal ref={ref} onClick={handleClick}>
				<SearchBar onSearch={onSearch} onClose={onClose} />
				<SearchResults results={results} onClose={onClose} />
			</SearchModal>
		);
	},
);

export default Search;
