name: Accessibility Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: pnpm install
      - run: pnpm run test:e2e:ci
